// assault.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 14 total shaders

textures/assault/atool_m02
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/atruss_m06a
{
	cull disable
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}

textures/assault/machine_cl01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c01b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c03a
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c03e
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c04b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c05b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c06b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c07
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/metal_c06
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/metal_c07a
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/metal_c07ans
{
	qer_editorimage textures/assault/metal_c07a.tga
	surfaceparm nonsolid
	surfaceparm trans
	implicitMap textures/assault/metal_c07a.tga
}

textures/assault/trim_c01
{
	surfaceparm metalsteps
	implicitMap -
}
