// awf_props.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 3 total shaders

textures/awf_props/tool_m01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/awf_props/tool_m06
{
	surfaceparm metalsteps
	implicitMap -
}

textures/awf_props/tool_m07
{
	cull disable
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
}
