// bunker_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 4 total shaders

textures/bunker_sd/extwall01_sand
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/extwall02_sand
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/girder01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/girder02
{
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/girder03
{
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/tinroof01
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/wirefence01
{
	cull none
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	implicitMask -
}


