// egypt_walls_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 21 total shaders

textures/egypt_walls_sd/stucco01_decor01_phong
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco01_decor01.tga
}

textures/egypt_walls_sd/stucco01_phong
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco01.tga
}

textures/egypt_walls_sd/stucco02
{
	qer_editorimage textures/egypt_walls_sd/stucco02.tga
	q3map_nonplanar
	q3map_shadeangle 60
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/egypt_walls_sd/stucco02.tga
		blendFunc filter
	}
}

textures/egypt_walls_sd/stucco02_04blend
{
	q3map_nonplanar
	q3map_shadeangle 30
	implicitMap -
}

textures/egypt_walls_sd/stucco03
{
	q3map_nonplanar
	q3map_shadeangle 60
	implicitMap -
}

textures/egypt_walls_sd/stucco04
{
	q3map_nonplanar
	q3map_shadeangle 60
	implicitMap -
}

textures/egypt_walls_sd/stucco07a
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07a_nonsolid
{
	surfaceparm nonsolid
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_walls_sd/stucco07a
}

textures/egypt_walls_sd/stucco07b
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07c
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco07d
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08a
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08b
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08c
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08d
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco08e
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09a
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09b
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09c
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09d
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09e
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/stucco09f
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_walls_sd/wood_c05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/egypt_walls_sd/wood_c06
{
	surfaceparm woodsteps
	implicitMap -
}

textures/egypt_walls_sd/wood_test
{
	surfaceparm woodsteps
	implicitMap -
}
