// tobruk_wall_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/tobruk_wall_sd/tobruk_wall_base7_phong
{
	q3map_nonplanar
	q3map_shadeangle 135
	implicitMap textures/tobruk_wall_sd/tobruk_wall_base7.tga
}
